#version: '3.8'
#
#services:
#  app:
#    image: arjunrathod1996/scmproject-githubactions
#    container_name: scm-app
#    ports:
#      - "8080:8081"  # Host 8080 → App's internal 8081
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/SCM
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root


version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: scm-mysql
    environment:
      MYSQL_DATABASE: SCM
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  app:
    image: arjunrathod1996/scmproject-githubactions
    container_name: scm-app
    ports:
      - "8080:8081"  # Host 8080 → App's internal 8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/SCM
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
