#version: '3.8'
#
#services:
#  app:
#    image: arjunrathod1996/scmproject-githubactions
#    container_name: scm-app
#    ports:
#      - "8080:8081"  # Host 8080 → App's internal 8081
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/SCM
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root


#version: '3.8'
#
#services:
#  mysql:
#    image: mysql:8
#    container_name: scm-mysql
#    environment:
#      MYSQL_DATABASE: SCM
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#      MYSQL_ROOT_PASSWORD: root
#    ports:
#      - "3306:3306"
#
#  app:
#    image: arjunrathod1996/scmproject-githubactions
#    container_name: scm-app
#    ports:
#      - "8080:8081"  # Host 8080 → App's internal 8081
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/SCM
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#    depends_on:
#      - mysql


version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: scm-mysql
    environment:
      MYSQL_DATABASE: SCM
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - scm-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false   # Disable security (no username/password)
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - scm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - scm-network

  app:
    image: arjunrathod1996/scmproject-githubactions
    container_name: scm-app
    ports:
      - "8080:8081"  # host:container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/SCM
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
    depends_on:
      mysql:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    networks:
      - scm-network

networks:
  scm-network:
    driver: bridge
